server:
  port: 9999

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
    #调整页面路径
    prefix: classpath:/templates/
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true